class PackageError(Exception):pass
class AlreadyInstalled(PackageError):pass
class InstallError(PackageError):pass
class NotInstalled(PackageError):pass
class VersionError(PackageError):pass
class MetadataError(PackageError):pass
class UninstallError(PackageError):pass
class PermissionDenied(UninstallError):pass
class StreamError(PackageError):pass
class HTTPError(PackageError):pass
class NotFound(PackageError):pass
class HTTPNotFound(NotFound,HTTPError):pass
class DownloadError(PackageError):pass
class PyPIError(PackageError):pass
class UserError(PyPIError):pass
class PyPIDownloadError(PyPIError,DownloadError):pass
class UserNotFound(UserError,NotFound):pass
class PackageWarning(Warning):pass
